from pathlib import Path
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


ROOT = Path.cwd()
OUT = ROOT / "output" / "acceptance_checklist.pdf"
OUT.parent.mkdir(parents=True, exist_ok=True)


styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "TitleCustom",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontSize=20,
    leading=24,
    spaceAfter=12,
)

subtitle_style = ParagraphStyle(
    "Subtitle",
    parent=styles["Normal"],
    alignment=TA_CENTER,
    fontSize=10,
    leading=14,
    spaceAfter=10,
)

heading = ParagraphStyle(
    "Heading",
    parent=styles["Heading2"],
    fontSize=13,
    leading=16,
    spaceBefore=8,
    spaceAfter=8,
)

small = ParagraphStyle(
    "Small",
    parent=styles["Normal"],
    fontSize=8,
    leading=10,
)

normal = ParagraphStyle(
    "NormalCustom",
    parent=styles["Normal"],
    fontSize=9,
    leading=13,
)


def footer(canvas, doc):
    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        7,
    )

    canvas.drawString(
        18 * mm,
        10 * mm,
        "Nifty 100 Financial Intelligence Platform - Final Acceptance Checklist",
    )

    canvas.drawRightString(
        A4[0] - 18 * mm,
        10 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


doc = SimpleDocTemplate(
    str(OUT),
    pagesize=A4,
    rightMargin=14 * mm,
    leftMargin=14 * mm,
    topMargin=15 * mm,
    bottomMargin=16 * mm,
)

story = []


# ============================================================
# COVER / SIGN-OFF SUMMARY
# ============================================================

story.append(
    Paragraph(
        "NIFTY 100 FINANCIAL INTELLIGENCE PLATFORM",
        title_style,
    )
)

story.append(
    Paragraph(
        "D45 - Final Acceptance Checklist",
        styles["Heading1"],
    )
)

story.append(
    Paragraph(
        f"Checklist date: {date.today().strftime('%d %B %Y')}",
        subtitle_style,
    )
)

story.append(
    Spacer(1, 6 * mm)
)

summary_data = [
    ["Item", "Final Status"],
    ["Acceptance gates", "20 / 20 verified"],
    ["Mandatory deliverables reviewed", "22 / 22 completed before checklist"],
    ["D-23 Acceptance Checklist", "Generated by this document"],
    ["Automated tests", "94 passing"],
    ["Company universe", "92 companies"],
    ["FastAPI endpoints", "16"],
    ["Company tearsheets", "92 PDFs"],
    ["Sector reports", "11 PDFs"],
    ["Analyst guide", "12 pages"],
]

summary_table = Table(
    summary_data,
    colWidths=[
        75 * mm,
        85 * mm,
    ],
)

summary_table.setStyle(
    TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8E8E8")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
        ]
    )
)

story.append(summary_table)

story.append(
    Spacer(1, 8 * mm)
)

story.append(
    Paragraph(
        "Final Sign-Off",
        heading,
    )
)

signoff_data = [
    ["Prepared / Reviewed By", "________________________________________"],
    ["Date", date.today().strftime("%d-%m-%Y")],
    ["Team Lead Name", "________________________________________"],
    ["Team Lead Signature", "________________________________________"],
    ["Team Lead Sign-Off Date", "________________________________________"],
]

signoff_table = Table(
    signoff_data,
    colWidths=[
        55 * mm,
        105 * mm,
    ],
)

signoff_table.setStyle(
    TableStyle(
        [
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]
    )
)

story.append(signoff_table)

story.append(
    Spacer(1, 6 * mm)
)

story.append(
    Paragraph(
        (
            "<b>Sign-off note:</b> The technical acceptance checks are "
            "complete. The Team Lead signature above must be added before "
            "the checklist is treated as formally signed off."
        ),
        normal,
    )
)

story.append(PageBreak())


# ============================================================
# 20 ACCEPTANCE GATES
# ============================================================

story.append(
    Paragraph(
        "20 Mandatory Acceptance Gates",
        styles["Heading1"],
    )
)

acceptance = [
    (
        "AC-01",
        "Data Coverage",
        "PASS",
        "92 companies present.",
    ),
    (
        "AC-02",
        "Time Coverage",
        "PASS",
        "84/92 companies (91.3%) have at least 10 years of P&L, BS and CF records.",
    ),
    (
        "AC-03",
        "Schema Integrity",
        "PASS",
        "PRAGMA foreign_key_check returned 0 errors.",
    ),
    (
        "AC-04",
        "KPI Completeness",
        "PASS",
        "financial_ratios contains 1,164 rows and 26 populated KPI columns.",
    ),
    (
        "AC-05",
        "Revenue CAGR Accuracy",
        "PASS",
        "TCS, INFY and RELIANCE manual 5-year CAGR checks matched stored values with 0.0 difference.",
    ),
    (
        "AC-06",
        "ROE Accuracy",
        "PASS",
        "Five manual company checks were within the allowed +/-5 percentage points.",
    ),
    (
        "AC-07",
        "Screener Accuracy",
        "PASS",
        "Quality filter returned 37 companies, within required 10-50 range.",
    ),
    (
        "AC-08",
        "Dashboard Load",
        "PASS",
        "Company Profile screen manually verified to load in under 3 seconds.",
    ),
    (
        "AC-09",
        "Dashboard Export",
        "PASS",
        "Screener CSV downloaded successfully with valid headers and company data.",
    ),
    (
        "AC-10",
        "PDF Quality",
        "PASS",
        "Five tearsheets visually reviewed. No clipping, text overflow or overlapping content observed.",
    ),
    (
        "AC-11",
        "API Health",
        "PASS",
        "GET /api/v1/health returned HTTP 200 and healthy status.",
    ),
    (
        "AC-12",
        "API Accuracy",
        "PASS",
        "TCS ratios API returned 13 annual ratio rows.",
    ),
    (
        "AC-13",
        "API Screener Consistency",
        "PASS",
        "API and Module 3 both returned 37 companies; differences = 0.",
    ),
    (
        "AC-14",
        "Peer Coverage",
        "PASS",
        "11 peer groups verified with no orphan members.",
    ),
    (
        "AC-15",
        "Cluster Coverage",
        "PASS",
        "92 companies assigned across cluster IDs 0-4 with no null cluster IDs.",
    ),
    (
        "AC-16",
        "NLP Coverage",
        "PASS",
        "All 92 companies contain at least one pro and one con entry.",
    ),
    (
        "AC-17",
        "Report Coverage",
        "PASS",
        "92 company tearsheets present; none below 50 KB.",
    ),
    (
        "AC-18",
        "Test Coverage",
        "PASS",
        "94 pytest tests collected and passing; zero failures.",
    ),
    (
        "AC-19",
        "DQ Documentation",
        "PASS",
        "validation_failures.csv present with required fields; 344 documented rows.",
    ),
    (
        "AC-20",
        "Documentation",
        "PASS",
        "analyst_guide.pdf contains 12 pages and includes Screener and Dashboard guidance.",
    ),
]

gate_data = [
    [
        Paragraph("<b>Gate</b>", small),
        Paragraph("<b>Area</b>", small),
        Paragraph("<b>Status</b>", small),
        Paragraph("<b>Evidence</b>", small),
    ]
]

for code, area, status, evidence in acceptance:
    gate_data.append(
        [
            Paragraph(code, small),
            Paragraph(area, small),
            Paragraph(f"<b>{status}</b>", small),
            Paragraph(evidence, small),
        ]
    )

gate_table = Table(
    gate_data,
    repeatRows=1,
    colWidths=[
        16 * mm,
        34 * mm,
        18 * mm,
        110 * mm,
    ],
)

gate_table.setStyle(
    TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8E8E8")),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
    )
)

story.append(gate_table)

story.append(PageBreak())


# ============================================================
# 23 DELIVERABLES
# ============================================================

story.append(
    Paragraph(
        "23 Mandatory Deliverables",
        styles["Heading1"],
    )
)

deliverables = [
    ("D-01", "nifty100.db", "PASS"),
    ("D-02", "load_audit.csv", "PASS"),
    ("D-03", "validation_failures.csv", "PASS"),
    ("D-04", "exploratory_queries.sql", "PASS"),
    ("D-05", "financial_ratios table", "PASS"),
    ("D-06", "capital_allocation.csv", "PASS"),
    ("D-07", "screener_output.xlsx", "PASS"),
    ("D-08", "screener_config.yaml", "PASS"),
    ("D-09", "peer_comparison.xlsx", "PASS"),
    ("D-10", "92 radar chart PNG files", "PASS"),
    ("D-11", "Streamlit dashboard - 8 screens", "PASS"),
    ("D-12", "valuation_summary.xlsx", "PASS"),
    ("D-13", "cashflow_intelligence.xlsx", "PASS"),
    ("D-14", "pros_cons_generated.csv", "PASS"),
    ("D-15", "analysis_parsed.csv", "PASS"),
    ("D-16", "92 company tearsheets", "PASS"),
    ("D-17", "11 sector reports", "PASS"),
    ("D-18", "Portfolio summary PDF", "PASS"),
    ("D-19", "cluster_labels.csv", "PASS"),
    ("D-20", "FastAPI server + OpenAPI + Postman", "PASS"),
    ("D-21", "pytest_report.html", "PASS"),
    ("D-22", "analyst_guide.pdf", "PASS"),
    ("D-23", "acceptance_checklist.pdf", "GENERATED - SIGNATURE REQUIRED"),
]

deliverable_data = [
    [
        Paragraph("<b>ID</b>", small),
        Paragraph("<b>Deliverable</b>", small),
        Paragraph("<b>Status</b>", small),
    ]
]

for code, item, status in deliverables:
    deliverable_data.append(
        [
            Paragraph(code, small),
            Paragraph(item, small),
            Paragraph(status, small),
        ]
    )

deliverable_table = Table(
    deliverable_data,
    repeatRows=1,
    colWidths=[
        18 * mm,
        105 * mm,
        55 * mm,
    ],
)

deliverable_table.setStyle(
    TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8E8E8")),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
    )
)

story.append(deliverable_table)

story.append(
    Spacer(1, 8 * mm)
)

story.append(
    Paragraph(
        "Final Technical Conclusion",
        heading,
    )
)

story.append(
    Paragraph(
        (
            "All 20 technical acceptance gates have been verified as PASS. "
            "All mandatory project deliverables D-01 through D-22 have been "
            "reviewed and verified. D-23 is generated by this checklist. "
            "Formal project closure requires the Team Lead signature and "
            "date on the sign-off section."
        ),
        normal,
    )
)


doc.build(
    story,
    onFirstPage=footer,
    onLaterPages=footer,
)


print("=== ACCEPTANCE CHECKLIST CREATED ===")
print("File:", OUT.resolve())
print("Size:", OUT.stat().st_size, "bytes")

try:
    from pypdf import PdfReader

    reader = PdfReader(str(OUT))

    print(
        "Pages:",
        len(reader.pages),
    )

except Exception as exc:
    print(
        "Page verification skipped:",
        exc,
    )
